name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: read-all

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          activate-environment: pari-jupyter-test
          environment-file: test/environment.yml
          python-version: 3.9
          auto-activate-base: false
      - name: Conda list
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Install pari-jupyter
        shell: bash -l {0}
        run: pip install --verbose --no-build-isolation .
      - name: Run test
        shell: bash -l {0}
        run: |
          cd test
          python test_pari_jupyter_kernel.py
